platform:
  accel: "gpu"
  cache_dir: "/home/iwe41/Documents/dataload/"
  thermompnn_dir: "/home/iwe41/github/ThermoMPNN"

data_loc:
        megascale_csv: "/nas/longleaf/home/dieckhau/protein-stability/enzyme-stability/data/mega_scale/Processed_K50_dG_datasets/Tsuboyama2023_Dataset2_Dataset3_20230416.csv"
        megascale_splits: "/nas/longleaf/home/dieckhau/protein-stability/enzyme-stability/data/mega_scale/mega_splits.pkl"
        megascale_pdbs: "/nas/longleaf/home/dieckhau/protein-stability/enzyme-stability/data/mega_scale/AlphaFold_model_PDBs/"

        fireprot_csv: "/home/iwe41/Documents/dataload/fireprot/csvs/4_fireprotDB_bestpH.csv"
        fireprot_splits: "/home/iwe41/Documents/dataload/fireprot/csvs/fireprot_splits.pkl"
        fireprot_pdbs: "/home/iwe41/Documents/dataload/fireprot/pdbs/"

        S4038_csv: "/home/iwe41/Documents/dataload/S4038/csvs/S4038_final.csv"
        S4038_splits: "/home/iwe41/Documents/dataload/S4038/csvs/S4038_splits.pkl"
        S4038_pdbs: "/home/iwe41/Documents/dataload/S4038/pdbs"
